ASPNET_Core_1_0/Models/Fields/Account.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MatterCentral.Models
{
    public class Account
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ZipCode { get; set; }
        public bool IsActive { get; set; }
        public string ARAccountingCode { get; set; }
        public string APAccountingCode { get; set; }
        public string ExternalAccountingId { get; set; }
        public string TaxId { get; set; }

        public int? TypeId { get; set; }
        public AccountType Type { get; set; }

        public int? CityId { get; set; }
        public City City { get; set; }

        public int? PaymentTermId { get; set; }
        public PaymentTerm PaymentTerm { get; set; }
    }
}

ASPNET_Core_1_0/Models/Fields/AccountType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MatterCentral.Models
{
    public class AccountType
    {
        public int Id { get; set; }
        public bool IsActive { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
        public bool ShowOnAuthorization { get; set; }
    }
}

ASPNET_Core_1_0/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using MatterCentral.Models;
using MatterCentral.Models.AccountViewModels;
using MatterCentral.Services;


namespace MatterCentral.Controllers
{
    [Authorize]
    public class AccountController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IEmailSender _emailSender;
        private readonly ISmsSender _smsSender;
        private readonly ILogger _logger;

        public AccountController(
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            IEmailSender emailSender,
            ISmsSender smsSender,
            ILoggerFactory loggerFactory)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _emailSender = emailSender;
            _smsSender = smsSender;
            _logger = loggerFactory.CreateLogger<AccountController>();
        }

        //
        // GET: /Account/Login
        [HttpGet]
        [AllowAnonymous]
        public IActionResult Login(string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }

        //
        // POST: /Account/Login
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginViewModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                // This doesn't count login failures towards account lockout
                // To enable password failures to trigger account lockout, set lockoutOnFailure: true
                var result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    _logger.LogInformation(1, "User logged in.");
                    return RedirectToLocal(returnUrl);
                }
                if (result.RequiresTwoFactor)
                {
                    return RedirectToAction(nameof(SendCode), new { ReturnUrl = returnUrl, RememberMe = model.RememberMe });
                }
                if (result.IsLockedOut)
                {
                    _logger.LogWarning(2, "User account locked out.");
                    return View("Lockout");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return View(model);
                }
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        //
        // GET: /Account/Register
        [HttpGet]
        [AllowAnonymous]
        public IActionResult Register(string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }

        //
        // POST: /Account/Register
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegisterViewModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = model.Email, Email = model.Email };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    // For more information on how to enable account confirmation and password reset please visit http://go.microsoft.com/fwlink/?LinkID=532713
                    // Send an email with this link
                    //var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                    //var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = user.Id, code = code }, protocol: HttpContext.Request.Scheme);
                    //await _emailSender.SendEmailAsync(model.Email, "Confirm your account",
                    //    $"Please confirm your account by clicking this link: <a href='{callbackUrl}'>link</a>");
                    await _signInManager.SignInAsync(user, isPersistent: false);
                    _logger.LogInformation(3, "User created a new account with password.");
                    return RedirectToLocal(returnUrl);
                }
                AddErrors(result);
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        //
        // POST: /Account/LogOff
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LogOff()
        {
            await _signInManager.SignOutAsync();
            _logger.LogInformation(4, "User logged out.");
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }

        //
        // POST: /Account/ExternalLogin
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public IActionResult ExternalLogin(string provider, string returnUrl = null)
        {
            // Request a redirect to the external login provider.
            var redirectUrl = Url.Action("ExternalLoginCallback", "Account", new { ReturnUrl = returnUrl });
            var properties = _signInManager.ConfigureExternalAuthenticationProperties(provider, redirectUrl);
            return Challenge(properties, provider);
        }

        //
        // GET: /Account/ExternalLoginCallback
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> ExternalLoginCallback(string returnUrl = null, string remoteError = null)
        {
            if (remoteError != null)
            {
                ModelState.AddModelError(string.Empty, $"Error from external provider: {remoteError}");
                return View(nameof(Login));
            }
            var info = await _signInManager.GetExternalLoginInfoAsync();
            if (info == null)
            {
                return RedirectToAction(nameof(Login));
            }

            // Sign in the user with this external login provider if the user already has a login.
            var result = await _signInManager.ExternalLoginSignInAsync(info.LoginProvider, info.ProviderKey, isPersistent: false);
            if (result.Succeeded)
            {
                _logger.LogInformation(5, "User logged in with {Name} provider.", info.LoginProvider);
                return RedirectToLocal(returnUrl);
            }
            if (result.RequiresTwoFactor)
            {
                return RedirectToAction(nameof(SendCode), new { ReturnUrl = returnUrl });
            }
            if (result.IsLockedOut)
            {
                return View("Lockout");
            }
            else
            {
                // If the user does not have an account, then ask the user to create an account.
                ViewData["ReturnUrl"] = returnUrl;
                ViewData["LoginProvider"] = info.LoginProvider;
                var email = info.Principal.FindFirstValue(ClaimTypes.Email);
                return View("ExternalLoginConfirmation", new ExternalLoginConfirmationViewModel { Email = email });
            }
        }

        //
        // POST: /Account/ExternalLoginConfirmation
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ExternalLoginConfirmation(ExternalLoginConfirmationViewModel model, string returnUrl = null)
        {
            if (ModelState.IsValid)
            {
                // Get the information about the user from the external login provider
                var info = await _signInManager.GetExternalLoginInfoAsync();
                if (info == null)
                {
                    return View("ExternalLoginFailure");
                }
                var user = new ApplicationUser { UserName = model.Email, Email = model.Email };
                var result = await _userManager.CreateAsync(user);
                if (result.Succeeded)
                {
                    result = await _userManager.AddLoginAsync(user, info);
                    if (result.Succeeded)
                    {
                        await _signInManager.SignInAsync(user, isPersistent: false);
                        _logger.LogInformation(6, "User created an account using {Name} provider.", info.LoginProvider);
                        return RedirectToLocal(returnUrl);
                    }
                }
                AddErrors(result);
            }

            ViewData["ReturnUrl"] = returnUrl;
            return View(model);
        }

        // GET: /Account/ConfirmEmail
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> ConfirmEmail(string userId, string code)
        {
            if (userId == null || code == null)
            {
                return View("Error");
            }
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return View("Error");
            }
            var result = await _userManager.ConfirmEmailAsync(user, code);
            return View(result.Succeeded ? "ConfirmEmail" : "Error");
        }

        //
        // GET: /Account/ForgotPassword
        [HttpGet]
        [AllowAnonymous]
        public IActionResult ForgotPassword()
        {
            return View();
        }

        //
        // POST: /Account/ForgotPassword

ASPNET_Core_1_0/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MatterCentral.Data;
using MatterCentral.Models;

namespace MatterCentral.Controllers
{
    public class AccountsController : Controller
    {
        private readonly ALCContext _context;

        public AccountsController(ALCContext context)
        {
            _context = context;
        }

        // GET: Accounts
        public async Task<IActionResult> Index()
        {
            var aLCContext = _context.Accounts.Include(a => a.Type);
            return View(await aLCContext.ToListAsync());
        }
        
        // GET: Authorizations/List
        public async Task<IActionResult> List()
        {
            var model = new ListAccountViewModel(await _context.Accounts.Include(a => a.Type).ToListAsync());
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> GetStates(string _CountryId)
        {
            int CountryId;
            if(!int.TryParse(_CountryId, out CountryId)) {
                return null;
            }
            var States = await _context.States.Where(s => s.CountryId == CountryId).ToListAsync();
            return PartialView("_GetStates", new GetStatesViewModel(States));
        }

        [HttpGet]
        public async Task<IActionResult> GetCities(string _StateId)
        {
            int StateId;
            if (!int.TryParse(_StateId, out StateId)) {
                return null;
            }
            var Cities = await _context.Cities.Where(c => c.StateId == StateId).ToListAsync();
            return PartialView("_GetCities", new GetCitiesViewModel(Cities));
        }

        // GET: Accounts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var account = await _context.Accounts
                .Include(a => a.Type)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (account == null)
            {
                return NotFound();
            }

            return View(account);
        }

        // GET: Accounts/Create
        public async Task<IActionResult> Create()
        {
            var viewModel = new CreateAccountViewModel(new Account(), 
                                                        await _context.AccountTypes.ToListAsync(), 
                                                        await _context.PaymentTerms.ToListAsync(), 
                                                        await _context.Countries.ToListAsync()
                                                        );
            return View(viewModel);
        }

        // POST: Accounts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,TypeId")] Account account)
        {
            if (ModelState.IsValid)
            {
                _context.Add(account);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["TypeId"] = new SelectList(_context.AccountTypes, "Id", "Id", account.TypeId);
            return View(account);
        }

        // GET: Accounts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var account = await _context.Accounts.SingleOrDefaultAsync(m => m.Id == id);
            if (account == null)
            {
                return NotFound();
            }
            ViewData["TypeId"] = new SelectList(_context.AccountTypes, "Id", "Id", account.TypeId);
            return View(account);
        }

        // POST: Accounts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,TypeId")] Account account)
        {
            if (id != account.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(account);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AccountExists(account.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TypeId"] = new SelectList(_context.AccountTypes, "Id", "Id", account.TypeId);
            return View(account);
        }

        // GET: Accounts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var account = await _context.Accounts
                .Include(a => a.Type)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (account == null)
            {
                return NotFound();
            }

            return View(account);
        }

        // POST: Accounts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var account = await _context.Accounts.SingleOrDefaultAsync(m => m.Id == id);
            _context.Accounts.Remove(account);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AccountExists(int id)
        {
            return _context.Accounts.Any(e => e.Id == id);
        }
    }
}

ASPNET_Core_1_0/Views/Accounts/Create.cshtml
@model MatterCentral.Models.CreateAccountViewModel

@{
    ViewData["Title"] = "Create";  
}
 
<h2>Create</h2> 

<h4>Account</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create"  style="width:500px;">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div  class="col-lg-2" style="width:200px;">
                <div class="form-group">
                    <label asp-for="Account.Name" class="control-label"></label>
                    <input asp-for="Account.Name" class="form-control" />
                    <span asp-validation-for="Account.Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Country" class="control-label"></label>
                    <select asp-for="Country" class="form-control" id="CountrySelector" asp-items="Model.Countries"></select>
                </div>
                <div class="form-group">
                    <label asp-for="State" class="control-label"></label>
                    <select id="StateSelector" name="StateId" class="form-control"></select>
                </div>
                <div class="form-group">
                    <label asp-for="Account.City" class="control-label"></label>
                    <select id="CitySelector" name="CityId" class="form-control"></select>
                </div>
                <div class="form-group">
                    <label asp-for="Account.ZipCode" class="control-label"></label>
                    <input asp-for="Account.ZipCode" class="form-control" />
                    <span asp-validation-for="Account.ZipCode" class="text-danger"></span>
                </div>
            </div>
            @*<select name="ShipperId" class="form-control">
                @foreach (var item in Model.ShipperList) {
                    <option value="@item.Id" selected="@(item.Id==Model.ShipperId)">@item.Value</option>
                }
            </select>*@
            <div class="col-lg-2" style="width:200px;">
                <div class="form-group">
                    <label asp-for="Account.IsActive" class="control-label"></label>
                    <input asp-for="Account.IsActive" class="form-control" />
                    <span asp-validation-for="Account.IsActive" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Account.ARAccountingCode" class="control-label"></label>
                    <input asp-for="Account.ARAccountingCode" class="form-control" />
                    <span asp-validation-for="Account.ARAccountingCode" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Account.APAccountingCode" class="control-label"></label>
                    <input asp-for="Account.APAccountingCode" class="form-control" />
                    <span asp-validation-for="Account.APAccountingCode" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Account.ExternalAccountingId" class="control-label"></label>
                    <input asp-for="Account.ExternalAccountingId" class="form-control" />
                    <span asp-validation-for="Account.ExternalAccountingId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Account.TaxId" class="control-label"></label>
                    <input asp-for="Account.TaxId" class="form-control" />
                    <span asp-validation-for="Account.TaxId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Account.TypeId" class="control-label"></label>
                    <select asp-for="Account.TypeId" class="form-control" asp-items="Model.AccountTypes"></select>
                </div>
            </div>


            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}


    <script type="text/javascript">
        $(document).ready(function () {

            var StatesUrl = '@Url.Action("GetStates", "Accounts", new { _CountryId = "PLACEHOLDER" } )';
            var CitiesUrl = '@Url.Action("GetCities", "Accounts", new { _StateId = "PLACEHOLDER" } )';
            // On CountrySelector change, generate State and City lists
            $('#CountrySelector').change(function () {
                
                // Get Country
                var Country = $('#CountrySelector').val();

                $.get(StatesUrl.replace('PLACEHOLDER', Country), function (data) {

                    // Clear City
                    $("#CitySelector").html("");

                    // Update State
                    $("#StateSelector").html(data);
                });

            });

            // On StateSelector change, generate State and City lists
            $('#StateSelector').change(function () {

                // Get State
                var State = $('#StateSelector').val();

                $.get(CitiesUrl.replace('PLACEHOLDER', State), function (data) {
                    
                    // Update State
                    $("#CitySelector").html(data);
                });

            });


        });
    </script>

}

ASPNET_Core_1_0/Views/Accounts/Delete.cshtml
@model MatterCentral.Models.Account

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Account</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ASPNET_Core_1_0/Views/Accounts/Details.cshtml
@model MatterCentral.Models.Account

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Account</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ASPNET_Core_1_0/Views/Accounts/Edit.cshtml
@model MatterCentral.Models.Account

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Account</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TypeId" class="control-label"></label>
                <select asp-for="TypeId" class="form-control" asp-items="ViewBag.TypeId"></select>
                <span asp-validation-for="TypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ASPNET_Core_1_0/Views/Accounts/Index.cshtml
@model IEnumerable<MatterCentral.Models.Account>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type.Id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

ASPNET_Core_1_0/Views/Accounts/List.cshtml
@model MatterCentral.Models.ListAccountViewModel


@{ 
    Layout = "_FieldItemList";
}

<table class="footable table table-stripped toggle-arrow-tiny" data-page-size="15">
    <thead>
        <tr>
            <th data-toggle="true">Id</th>
            <th data-toggle="true">Name</th>
            <th data-toggle="true">Type</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Accounts) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type.Title)
                </td>
                @*<td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>*@
                <td class="text-right">
                    <div class="btn-group">
                        <button class="btn-white btn btn-xs" onclick="@Url.Action("View", "Accounts");">Details</button>
                        <button class="btn-white btn btn-xs" onclick="@Url.Action("View", "Accounts");">Edit</button>
                        <button class="btn-white btn btn-xs">Delete</button>
                    </div>
                </td>
            </tr>
        }
    </tbody>

    <tfoot>
        <tr>
            <td colspan="6">
                <ul class="pagination pull-right"></ul>
            </td>
        </tr>
    </tfoot>
</table>