ASPNET_Core_1_0/Models/Fields/Authorization.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MatterCentral.Models
{
    public class Authorization
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public string Buyer { get; set; }
        public DateTime Effective { get; set; }
        public DateTime Expiration { get; set; }
        
        public ISet<Commodity> Commodities { get; protected set; }
        
        public int? AccountId { get; set; }
        public Account Account { get; set; }

        public int? StatusId { get; set; }
        public AuthorizationStatus Status { get; set; }

        public int? ShipperId { get; set; }
        public Organization Shipper { get; set; }

        public int? ReceiverId { get; set; }
        public Organization Receiver { get; set; }
    }
}

ASPNET_Core_1_0/Controllers/AuthorizationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MatterCentral.Data;
using MatterCentral.Models;

namespace MatterCentral.Controllers
{
    public class AuthorizationController : Controller
    {
        private readonly ALCContext _context;

        public AuthorizationController(ALCContext context)
        {
            _context = context;
        }

        // GET: Authorizations
        public async Task<IActionResult> Index()
        {
            return View(await _context.Authorizations.ToListAsync());
        }

        // GET: Authorizations/List
        public async Task<IActionResult> List()
        {
            var model = new ListAuthorizationViewModel(await _context.Authorizations.ToListAsync());
            return View(model);
        }

        // GET: Authorizations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var authorization = await _context.Authorizations
                .SingleOrDefaultAsync(m => m.Id == id);
            if (authorization == null)
            {
                return NotFound();
            }

            return View(authorization);
        }

        // GET: Authorizations/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Authorizations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Number,AuthorizationTypeId,Status,Buyer,ShipperId,ReceiverId,Effective,Expiration")] Authorization authorization)
        {
            if (ModelState.IsValid)
            {
                _context.Add(authorization);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(authorization);
        }

        // GET: Authorizations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var authorization = await _context.Authorizations.SingleOrDefaultAsync(m => m.Id == id);
            if (authorization == null)
            {
                return NotFound();
            }
            return View(authorization);
        }

        // POST: Authorizations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Number,AuthorizationTypeId,Status,Buyer,ShipperId,ReceiverId,Effective,Expiration")] Authorization authorization)
        {
            if (id != authorization.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(authorization);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AuthorizationExists(authorization.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(authorization);
        }

        // GET: Authorizations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var authorization = await _context.Authorizations
                .SingleOrDefaultAsync(m => m.Id == id);
            if (authorization == null)
            {
                return NotFound();
            }

            return View(authorization);
        }

        // POST: Authorizations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var authorization = await _context.Authorizations.SingleOrDefaultAsync(m => m.Id == id);
            _context.Authorizations.Remove(authorization);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AuthorizationExists(int id)
        {
            return _context.Authorizations.Any(e => e.Id == id);
        }
    }
}

ASPNET_Core_1_0/Views/Authorization/Create.cshtml
@model MatterCentral.Models.Authorization

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Authorization</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Number" class="control-label"></label>
                <input asp-for="Number" class="form-control" />
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuthorizationTypeId" class="control-label"></label>
                <input asp-for="AuthorizationTypeId" class="form-control" />
                <span asp-validation-for="AuthorizationTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="Status" /> @Html.DisplayNameFor(model => model.Status)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Buyer" class="control-label"></label>
                <input asp-for="Buyer" class="form-control" />
                <span asp-validation-for="Buyer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShipperId" class="control-label"></label>
                <input asp-for="ShipperId" class="form-control" />
                <span asp-validation-for="ShipperId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReceiverId" class="control-label"></label>
                <input asp-for="ReceiverId" class="form-control" />
                <span asp-validation-for="ReceiverId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Effective" class="control-label"></label>
                <input asp-for="Effective" class="form-control" />
                <span asp-validation-for="Effective" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Expiration" class="control-label"></label>
                <input asp-for="Expiration" class="form-control" />
                <span asp-validation-for="Expiration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ASPNET_Core_1_0/Views/Authorization/Delete.cshtml
@model MatterCentral.Models.Authorization

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Authorization</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AuthorizationTypeId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AuthorizationTypeId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Buyer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Buyer)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ShipperId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ShipperId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ReceiverId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ReceiverId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Effective)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Effective)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Expiration)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Expiration)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ASPNET_Core_1_0/Views/Authorization/Details.cshtml
@model MatterCentral.Models.Authorization

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Authorization</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AuthorizationTypeId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AuthorizationTypeId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Buyer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Buyer)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ShipperId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ShipperId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ReceiverId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ReceiverId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Effective)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Effective)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Expiration)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Expiration)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ASPNET_Core_1_0/Views/Authorization/Edit.cshtml
@model MatterCentral.Models.Authorization

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Authorization</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Number" class="control-label"></label>
                <input asp-for="Number" class="form-control" />
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuthorizationTypeId" class="control-label"></label>
                <input asp-for="AuthorizationTypeId" class="form-control" />
                <span asp-validation-for="AuthorizationTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="Status" /> @Html.DisplayNameFor(model => model.Status)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Buyer" class="control-label"></label>
                <input asp-for="Buyer" class="form-control" />
                <span asp-validation-for="Buyer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShipperId" class="control-label"></label>
                <input asp-for="ShipperId" class="form-control" />
                <span asp-validation-for="ShipperId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReceiverId" class="control-label"></label>
                <input asp-for="ReceiverId" class="form-control" />
                <span asp-validation-for="ReceiverId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Effective" class="control-label"></label>
                <input asp-for="Effective" class="form-control" />
                <span asp-validation-for="Effective" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Expiration" class="control-label"></label>
                <input asp-for="Expiration" class="form-control" />
                <span asp-validation-for="Expiration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ASPNET_Core_1_0/Views/Authorization/Index.cshtml
@model IEnumerable<MatterCentral.Models.Authorization>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Number)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AuthorizationTypeId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Status)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Buyer)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ShipperId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ReceiverId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Effective)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Expiration)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AuthorizationTypeId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Buyer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ShipperId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReceiverId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Effective)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Expiration)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

ASPNET_Core_1_0/Views/Authorization/List.cshtml
@model MatterCentral.Models.ListAuthorizationViewModel


@{ 
    Layout = "_FieldItemList";
}

<table class="footable table table-stripped toggle-arrow-tiny" data-page-size="15">
    <thead>
        <tr>
            <th data-toggle="true">Number</th>
            <th data-toggle="true">Authorization Type</th>
            <th data-toggle="true">Status</th>
            <th data-toggle="true">Buyer</th>
            <th data-toggle="true">Shipper</th>
            <th data-toggle="true">Receiver</th>
            <th data-toggle="true">Effective</th>
            <th data-toggle="true">Expiration</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Authorizations) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Number)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AuthorizationType.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AuthorizationStatus.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Buyer)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Shipper.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Receiver.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Effective)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Expiration)
                </td>
                @*<td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>*@
                <td class="text-right">
                    <div class="btn-group">
                        <button class="btn-white btn btn-xs" onclick="@Url.Action("View", "Authorization");">Details</button>
                        <button class="btn-white btn btn-xs" onclick="@Url.Action("View", "Authorization");">Edit</button>
                        <button class="btn-white btn btn-xs">Delete</button>
                    </div>
                </td>
            </tr>
        }
    </tbody>

    <tfoot>
        <tr>
            <td colspan="6">
                <ul class="pagination pull-right"></ul>
            </td>
        </tr>
    </tfoot>
</table>