ASPNET_Core_1_0/Controllers/EcommerceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MatterCentral.Models;

namespace MatterCentral.Controllers
{
    public class EcommerceController : Controller
    {
        ///IRepository repository = Repository.Instance;


        public IActionResult ProductsGrid()
        {
            return View();
        }

        public IActionResult ProductsList()
        {
            return View();
        }

        public IActionResult FieldList()
        {
            List<string> fieldList = new List<string>{
                "ReceiveLocation", "Receiver", "ReceiverContact", "Shipper", "State", "Authorization"
            };

            return View(fieldList);
        }

        public IActionResult ProductEdit()
        {
            return View();
        }

        [HttpGet]
        public IActionResult AuthorizationEdit(string AuthorizationNumber)
        {
            //var Auth = 
               /// Repository.Authorizations.Where(a => a.AuthorizationNumber == AuthorizationNumber)
                //                         .First();
            return View(new Authorization());
        }

        [HttpPost]
        public IActionResult AuthorizationEdit(Authorization Auth)
        {
            return View(Auth);
        }

        [HttpGet]
        public ActionResult AddNewRow()
        {
            return PartialView("_RelatedFieldRow");
        }

        [HttpGet]
        public ActionResult EditField(string Field, int Id)
        {
            // Get the correct field list, then Try to load the Field item by Id
            ///object viewModel = GetViewModel(Field, Id);
            
            string view = "EditField/_Edit" + Field;
            return PartialView(view);
        }
        //[HttpGet]
        //public ActionResult EditAuthorization(int Id)
        //{
        //    var model = new EditAuthorizationViewModel(
        //                repository.AuthorizationList.FirstOrDefault(i => i.Id == Id),
        //                repository);
        //    return PartialView("EditField/_EditAuthorization", model);
        //}
        //[HttpPost]
        //public ActionResult EditAuthorization(EditAuthorizationViewModel item)
        //{
        //    var model = new Authorization(item.Id, item.Number, item.ShipperId, item.ReceiverId, item.ReceiverContactId, item.CountyId, item.SupplierId, item.ReceiveLocationId);
        //    if (ModelState.IsValid) {
        //        return PartialView("EditField/_FieldSaved", "Authorization");
        //    }
        //    else {
        //        return PartialView("EditField/_EditAuthorization", item);
        //    }
        //}
        //[HttpGet]
        //public ActionResult ListAuthorization(int Page, int ItemsPerPage)
        //{
        //    var model = new ListAuthorizationViewModel(repository, Page, ItemsPerPage);
        //    return PartialView("EditField/_EditAuthorization", model);
        //}

        //public object GetViewModel(string Field, int Id)
        //{
        //    switch (Field) {
        //        // Compound
        //        case "Authorization":
        //            return new EditAuthorizationViewModel(
        //                repository.AuthorizationList.FirstOrDefault(i => i.Id == Id),
        //                repository);
        //        case "County":
        //            return null;
        //        case "Supplier":
        //            return null;

        //        // Singular
        //        case "ReceiveLocation":
        //            return new EditReceiveLocationViewModel(
        //                repository.ReceiveLocationList.FirstOrDefault(i => i.Id == Id));
        //        case "Receiver":
        //            return new EditReceiverViewModel(
        //                repository.ReceiverList.FirstOrDefault(i => i.Id == Id));
        //        case "ReceiverContact":
        //            return new EditReceiverContactViewModel(
        //                repository.ReceiverContactList.FirstOrDefault(i => i.Id == Id));
        //        case "Shipper":
        //            return new EditShipperViewModel(
        //                repository.ShipperList.FirstOrDefault(i => i.Id == Id));
        //        case "State":
        //            return new EditStateViewModel(
        //                repository.StateList.FirstOrDefault(i => i.Id == Id));
        //        default:
        //            return null;

        //    }
        //}
        public IActionResult Orders()
        {
            return View();
        }

        public IActionResult ProductDetail()
        {
            return View();
        }

        public IActionResult Payments()
        {
            return View();
        }

        public IActionResult Cart()
        {
            return View();
        }

    }
}

ASPNET_Core_1_0/Views/Ecommerce/AuthorizationEdit.cshtml
@model MatterCentral.Models.Authorization


@{
    Layout = "_EditField";
    ViewData["Title"] = "ProductEdit";
}


@using (Html.BeginForm("AuthorizationEdit", "Ecommerce", FormMethod.Post)) {

    <fieldset class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>
        <input id="btnSubmitAuth" class="btn btn-primary pull-left" type="submit" value="Submit">
    </fieldset>
}

ASPNET_Core_1_0/Views/Ecommerce/FieldList.cshtml
@model List<string>

@{
    ViewData["Title"] = "ProductsList";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>E-commerce product list</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Dashboard_1", "Dashboards")">Home</a>
            </li>
            <li>
                <a>E-commerce</a>
            </li>
            <li class="active">
                <strong>Product list</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight ecommerce">


    <div class="ibox-content m-b-sm border-bottom">
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    @*<label class="control-label" for="value_type">Type</label>*@
                    <select id="fieldSelector" name="fieldSelector" class="form-control">
                        @foreach (string field in Model) {
                            <option value="@field">@field</option>
                        }
                        @*<option value="0" selected>Field 1</option>*@
                    </select>
                </div>
            </div>
        </div>
    </div>
    <div class="ibox-content m-b-sm border-bottom">
        <div class="row">
            @using (Html.BeginForm("EditField", "Ecommerce", FormMethod.Post)) {
                <div id="editFieldDiv">@*Render EditField partial view here.*@</div>
                <input id="FieldName" type="hidden" name="country" value="SomeField">
                <input id="btnSubmitAuth" class="btn btn-primary pull-left" type="submit" value="Submit">
            }
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-content">
                    @*Generate Tables for each field type*@
                    <table class="footable table table-stripped toggle-arrow-tiny" data-page-size="15">
                        <thead>
                            <tr>
                                <th data-toggle="true">Field Attribute 1</th>
                                <th data-toggle="true">Field Attribute 2</th>
                                <th data-toggle="true">Field Attribute 3</th>
                            </tr>
                        </thead>

                        <tfoot>
                            <tr>
                                <td colspan="6">
                                    <ul class="pagination pull-right"></ul>
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                                @*
                        <table class="footable table table-stripped toggle-arrow-tiny" data-page-size="15">
                            <thead>
                                <tr>
                                    <th data-toggle="true">Authorization Number</th>
                                    <th data-hide="all">Shipper</th>
                                    <th data-hide="all">Receiver</th>
                                    <th data-hide="all">Receiver Contact</th>
                                    <th data-hide="all">State</th>
                                    <th data-hide="all">County</th>
                                    <th data-hide="all">Supplier Number</th>
                                    <th data-hide="all">Supplier Name</th>
                                    <th data-hide="all">Recloc ID</th>
                                    <th data-hide="all">Recloc Name</th>
                                    <th class="text-right" data-sort-ignore="true">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach(Authorization item in Model){
                                    <tr>
                                        <td>@item.AuthorizationNumber</td>
                                        <td>@item.Shipper</td>
                                        <td>@item.Receiver</td>
                                        <td>@item.ReceiverContact</td>
                                        <td>@item.State</td>
                                        <td>@item.County</td>
                                        <td>@item.SupplierNumber</td>
                                        <td>@item.SupplierName</td>
                                        <td>@item.ReclocID</td>
                                        <td>@item.ReclocName</td>
                                        <td class="text-right">
                                            <div class="btn-group">
                                                <button class="btn-white btn btn-xs" onclick="location.href='@Url.Action("AuthorizationEdit", "Ecommerce",
                                                                                                            new { AuthorizationNumber = item.AuthorizationNumber })';return false;">Edit</button>
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="6">
                                        <ul class="pagination pull-right"></ul>
                                    </td>
                                </tr>
                            </tfoot>
                        </table>
                                *@

                </div>
            </div>
        </div>
    </div>


</div>

@section Styles {
    <environment names="Development">
        <link rel="stylesheet" href="~/lib/footable/css/footable.core.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/lib/footable/css/footable.core.min.css" />
    </environment>
}

@section Scripts {
    <environment names="Development,Staging,Production">
        <script src="~/lib/footable/dist/footable.all.min.js"></script>
    </environment>

    <script type="text/javascript">
        $(document).ready(function () {

            //$('.footable').footable();


            var url = '@Url.Action("EditField", "Ecommerce", new { Field = "PLACEHOLDER" } )';
            // On fieldSelector change, generate Edit Box
            $('#fieldSelector').change(function () {

                // Clear old form
                $("#editFieldDiv").html("");

                // Get Field Name
                var field = $('#fieldSelector').val();

                // 
                $("#FieldName").val(field);
                
                $.get(url.replace('PLACEHOLDER', field), function (data) {
                    $("#editFieldDiv").html(data);
                });

            });

            // Stay on page after submitting form
            var $form = $('form');
            $form.submit(function () {
                $.post($(this).attr('action'), $(this).serialize(), function (response) {
                    // do something here on success
                    $("#editFieldDiv").html(response);
                }, 'json');
                return false;
            });


        });
    </script>
}